[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    'oz/=lib/openzeppelin-contracts/contracts',
    'kleros/=lib/kleros/contracts',
    'delegatable/=lib/delegatable-sol/contracts/'
]
optimizer = true
optimizer_runs = 200
ignored_error_codes = []

[rpc_endpoints]
chiado = "https://rpc-chiado.gnosistestnet.com"
gnosis = "https://rpc.gnosischain.com"

[etherscan]
chiado = { key = "${GNOSISCHAIN_MAINNET_KEY}" }
gnosis = { key = "${GNOSISCHAIN_CHIADO_KEY}" }

[fmt]
line_length = 91
tab_width = 4
bracket_spacing = false
func_attrs_with_params_multiline = true
number_underscore = "thousands"
# See more config options https://github.com/gakonst/foundry/tree/master/config
