/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />
import { BigNumber } from "bignumber.js";

export interface GreeterContract extends Truffle.Contract<GreeterInstance> {
  "new"(
    _greeting: string,
    meta?: Truffle.TransactionDetails
  ): Promise<GreeterInstance>;
}

export interface GreeterInstance extends Truffle.ContractInstance {
  greet(txDetails?: Truffle.TransactionDetails): Promise<string>;

  setGreeting: {
    (_greeting: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse
    >;
    call(
      _greeting: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _greeting: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _greeting: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };
}
