[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'oz/=lib/openzeppelin-contracts/contracts',
    'kleros/=lib/kleros/contracts'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
