[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'oz/=lib/openzeppelin-contracts/contracts',
    'kleros/=lib/kleros/contracts',
    'delegatable/=lib/delegatable-sol/contracts/'
]

[fmt]
line_length = 91
tab_width = 4
bracket_spacing = false
func_attrs_with_params_multiline = true
number_underscore = "thousands"
# See more config options https://github.com/gakonst/foundry/tree/master/config
