[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'oz/=lib/openzeppelin-contracts/contracts',
    'kleros/=lib/kleros/contracts'
]

[fmt]
line_length = 91
tab_width = 4
bracket_spacing = false
# See more config options https://github.com/gakonst/foundry/tree/master/config
