#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod address;
pub mod contract_test;
pub mod ds_test;
pub mod ierc20;
pub mod ierc20_permit;
pub mod my_contract;
pub mod safe_erc20;
pub mod unipeer;
