name: Lints

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Cache Node Modules
      id: cache-npm-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Install
      if: steps.cache-npm-modules.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Run prettier
      run: yarn lint:check

    - name: Run solhint
      run: yarn hardhat check
