name: Contracts

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache Node Modules
      id: cache-npm-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Install
      if: steps.cache-npm-modules.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Start buidlerevm node
      run: |
        yarn exec buidler node &

    - name: Compile
      run: |
        yarn exec buidler typechain

    - name: Test
      run: |
        yarn exec buidler test --network localhost
      env:
        PRODUCTION: true
        REPORT_GAS: true
