name: Contracts

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Cache Node Modules
      id: cache-npm-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

    - name: Install
      if: steps.cache-npm-modules.outputs.cache-hit != 'true'
      run: |
        yarn install

    - name: Start hardhat network node
      run: |
        yarn hardhat node &

    - name: Compile
      run: |
        yarn hardhat compile
      env:
        PRODUCTION: true

    - name: Test
      run: |
        yarn hardhat test --network localhost
      env:
        PRODUCTION: true
        REPORT_GAS: true
        COINMARKET_API: ${{ secrets.COINMARKET_API }}

    - name: Test Coverage
      run: |
        yarn run coverage
